[project]
name = "t0-github-ci-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.117.1",
    "uvicorn>=0.37.0",
]
