name: TensorZero CI Diagnosis Bot

on:
  workflow_run:
    # TODO: Replace with the actual workflow(s) to monitor. This doesn't seem to work yet.
    workflows: ["Dummy CI Failure"]
    types:
      - completed

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  gather-diff-and-generate-patch:
    # TODO: only do this against main branch
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    name: Gather failure context and generate PR
    env:
      DIAGNOSTICS_DIR: diagnostics
    steps:
      # TODO: delete this before actually sending it out
      - name: Install GitHub CLI (act local only)
        run: |
          type -p gh >/dev/null || (
            sudo apt-get update &&
            sudo apt-get install -y gh
          )

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Gather PR metadata
        id: pr-info
        uses: actions/github-script@v7
        with:
          script: |
            const run = context.payload.workflow_run;
            const pr = run.pull_requests[0];

            if (!pr) {
              core.setFailed('No pull request found for the failing workflow run.');
              return;
            }

            core.setOutput('pr-number', pr.number);
            core.setOutput('base-ref', pr.base.ref);
            core.setOutput('head-ref', pr.head.ref);
            core.setOutput('head-sha', run.head_sha);
            core.setOutput('run-id', run.id);
            core.setOutput('run-attempt', run.run_attempt);
      
      - name: Prepare diagnostics workspace
        run: |
          mkdir -p "${DIAGNOSTICS_DIR}"

      - name: Fetch base branch for diff
        run: |
          git fetch origin "${{ steps.pr-info.outputs.base-ref }}"

      - name: Capture PR diff summary
        run: |
          git diff --stat "origin/${{ steps.pr-info.outputs.base-ref }}...${{ steps.pr-info.outputs.head-sha }}" > "${DIAGNOSTICS_DIR}/diff-summary.txt"
          export DIFF_SUMMARY_PATH="${DIAGNOSTICS_DIR}/diff-summary.txt"

      - name: Capture full PR diff
        run: |
          git diff "origin/${{ steps.pr-info.outputs.base-ref }}...${{ steps.pr-info.outputs.head-sha }}" > "${DIAGNOSTICS_DIR}/pr.diff"
          export FULL_DIFF_PATH="${DIAGNOSTICS_DIR}/pr.diff"

      # Consider also downloading artifacts here

      - name: Start TensorZero gateway
        run: |
          docker pull tensorzero/gateway:latest
          docker run -d --rm \
            --name tensorzero-gateway \
            -e TENSORZERO_CLICKHOUSE_URL=${{ secrets.CLICKHOUSE_URL }} \
            -e OPENAI_API_KEY=${{ secrets.OPENAIAPIKEY }} \
            -p 3000:3000 \
            tensorzero/gateway:latest --default-config

          for i in {1..20}; do
            curl -fsS http://localhost:3000/health && exit 0
            sleep 3
          done
          echo "Gateway never became ready" >&2
          exit 1

      - name: Call LLM to generate PR revision
        uses: shuyangli/t0-typescript-action@f3138660ed9c31c01b9f562d793c4ac40345b9ac
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAIAPIKEY }}
          tensorzero-base-url: http://localhost:3000
          diff-summary-path: diagnostics/diff-summary.txt
          full-diff-path: diagnostics/pr.diff
          artifacts-dir: artifacts
      
      - name: Upload diagnostics bundle
        uses: actions/upload-artifact@v4
        with:
          name: ci-failure-diagnostics
          path: |
            diagnostics/
            custom-action-artifacts/

      - name: Post placeholder comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number("${{ steps.pr-info.outputs.pr-number }}"),
              body: [
                `🤖 CI Failure Diagnostics (placeholder)`,
                '',
                `• Workflow Run ID: ${{ steps.pr-info.outputs.run-id }}`,
                `• Captured a diff summary and logs for analysis.`,
                `• LLM call not yet implemented. Replace the placeholder step in ci-failure-diagnosis.yml.`,
                '',
                `Artifacts: ci-failure-diagnostics`
              ].join('\n')
            });
      

      - name: Stop TensorZero gateway
        if: always()
        run: docker stop tensorzero-gateway
