name: TensorZero PR Feedback

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: read
  actions: read

jobs:
  create-pr-feedback:
    runs-on: ubuntu-latest
    name: Create PR Feedback
    steps:
      - name: Create PR Feedback
        uses: shuyangli/t0-typescript-action/create-pr-feedback@main
        with:
          token: ${{ github.token }}
